// src/hand_loader.cpp

#include "hand_loader.h"
#include <fstream>
#include <nlohmann/json.hpp>

using json = nlohmann::json;

/*
    Reads a JSON file (generated by the Python script),
    Extracts the 21 hand landmarks (each with x, y, z float values),
    And returns them as a C++ vector of Landmark structs.
*/
std::vector<Landmark> load_hand_landmarks(const char* filename) {
    std::ifstream file(filename);
    json data;
    file >> data;

    std::vector<Landmark> landmarks;
    for (const auto& point : data) {
        landmarks.push_back({
            point["x"].get<float>(),
            point["y"].get<float>(),
            point["z"].get<float>()
        });
    }

    return landmarks;
}
